### ISSUE TITLE
How to use in EspoCRM

### ISSUE THREAD

**Issue by MANEnterprise-Joseph** [telecastg/nested-teams-for-espocrm#1]
How do you use this extension with Espo. I uploaded the zip file in the extensions area but I still am creating teams the same way

**Comment by telecastg** [comment]
Please see Espo's forum for instructions.
Here's the link: forum.espocrm.com/forum/general/57059-team-visibility-and-sub-team
    On Monday, September 13, 2021, 07:33:23 AM PDT, MANEnterprise-Joseph ***@***.***> wrote:  
 
 


How do you use this extension with Espo. I uploaded the zip file in the extensions area but I still am creating teams the same way

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
